# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R82baBoxES27QgJ382OncR0c4HSLmoqR
"""

!git clone https://github.com/Gurleviks/Data_Man.git
import pandas as pd

data = pd.read_csv('//content/world_alcohol - world_alcohol.csv')

who_regions = ['Africa', 'Eastern Mediterranean', 'Europe']

filtered_data = data[data['WHO region'].isin(who_regions)]

filtered_data = filtered_data[['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value']]

print(filtered_data)